Express_delivery_management_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from home import views

urlpatterns = [
    url(r'^$', views.login),
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^ruler/', include('ruler.urls', namespace='ruler')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^courier/', include('courier.urls', namespace='courier')),
]

courier/urls.py
from django.conf.urls import url

from courier import views

urlpatterns = [
    url('courier_order_create', views.courier_order_create, name='courier_order_create'),
    url('courier_order_read', views.courier_order_read, name='courier_order_read'),
    url('courier_order_history', views.courier_order_history, name='courier_order_history'),
    url('courier_info', views.courier_info, name='courier_info'),
    url('courier_pw_set', views.courier_pw_set, name='courier_pw_set'),
    url('login', views.courier_login, name='login'),
    url('register', views.courier_register, name='register'),
    url('courier_charts', views.courier_charts, name='courier_charts'),
    url('order_detail/(?P<order_id>\d+)/', views.order_detail, name='order_detail'),
    url('order_add/(?P<order_id>\d+)/', views.order_add, name='order_add'),
    url('get_echarts', views.get_echarts, name='get_echarts')
]

home/urls.py
from django.conf.urls import url

from home import views

urlpatterns = [
    url(r'login', views.login, name='login'),
    url(r'register', views.register, name='register'),
    url(r'index', views.index, name='index'),
    url(r'logout', views.logout, name='logout'),
]

ruler/urls.py
from django.conf.urls import url

from ruler import views

urlpatterns = [
    url('login', views.ruler_login, name='login'),
    url('ruler_register', views.ruler_register, name='ruler_register'),
    url('ruler_user_read', views.ruler_user_read, name='ruler_user_read'),
    url('ruler_courier_read', views.ruler_courier_read, name='ruler_courier_read'),
    url('user_order_search', views.user_order_search, name='user_order_search'),
    url('courier_order_search', views.courier_order_search, name='courier_order_search'),
    url('ruler_user_order_read', views.ruler_user_order_read, name='ruler_user_order_read'),
    url('ruler_courier_order_read', views.ruler_courier_order_read, name='ruler_courier_order_read'),
    url('ruler_charts', views.ruler_charts, name='ruler_charts'),
    url('get_echarts', views.get_echarts, name='get_echarts'),
    url('user_detail/(?P<id>\d+)/', views.user_detail, name='user_detail'),
    url('courier_detail/(?P<id>\d+)/', views.courier_detail, name='courier_detail'),
    url('user_del/(?P<id>\d+)/', views.user_del, name='user_del'),
    url('courier_del/(?P<id>\d+)/', views.courier_del, name='courier_del'),
]

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    url('user_order_create', views.user_order_create, name='user_order_create'),
    url('user_order_search', views.user_order_search, name='user_order_search'),
    url('user_order_del', views.user_order_del, name='user_order_del'),
    # url('user_order_search_result/$', views.user_order_search_result, name='user_order_search_result'),
    url('user_order_history', views.user_order_history, name='user_order_history'),
    url('user_info', views.user_info, name='user_info'),
    url('user_pw_set', views.user_pw_set, name='user_pw_set'),
    url('user_charts', views.user_charts, name='user_charts'),
    url('create_orders', views.create_orders, name='create_orders'),
    url('get_echarts', views.get_echarts, name='get_echarts'),
    url('order_del/(?P<order_id>\d+)/', views.order_del, name='order_del'),
]

templates/courierOrderCreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/layui/css/layui.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/admin.css"/>
</head>
<body>
<div style="margin-top: 40px">
    <span style="margin-left: 5%;">按收件人姓名查找</span>
</div>
<hr class="layui-bg-blue">
<div class="layui-form" id="table-list">
    <table class="layui-table" lay-even lay-skin="nob">
        <colgroup>
            <col width="50">
            <col class="hidden-xs" width="50">
            <col class="hidden-xs" width="100">
            <col width="100">
            <col class="hidden-xs" width="100">
            <col width="80">
            <col width="150">
        </colgroup>
        <thead>
        <tr>
            <th class="hidden-xs">ID</th>
            <th class="hidden-xs">寄件人</th>
            <th>收件人</th>
            <th>发布时间</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td class="hidden-xs">{{ order.id }}</td>
                <td class="hidden-xs">{{ order.user.username }}</td>
                <td>{{ order.signer.signer_name }}</td>
                <td>{{ order.add_time }}</td>
                <td>
                    可接
                </td>
                <td>
                    <div class="layui-inline">
                        <a class="layui-btn layui-btn-mini layui-btn-normal" data-id="1"
                                href="{% url 'courier:order_detail' order.id%}"><i class="layui-icon">&#xe642;</i></a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="page-wrap">
        <ul class="pagination">
            <li class="disabled"><span>«</span></li>
            <li class="active"><span>1</span></li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">»</a>
            </li>
        </ul>
    </div>
</div>
<script src="/static/js/jquery/jquery-3.3.1.js"></script>
<script src="/static/admin/layui/layui.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/admin/js/common.js" type="text/javascript" charset="utf-8"></script>
{% csrf_token %}
<script>
    function order_detail(id) {
        var csrf = $('input[name = "csrfmiddlewaretoken"]').val()
        $.ajax({
            url: '/courier/order_detail/' + id + '/',
            type: 'POST',
            dataType: 'json',
            headers: {'X-CSRFToken': csrf},
            success: function (data) {

            },
            error: function (data) {
                alert('请求失败')
            }
        })
    }
</script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <title>快递管理模版</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/layui/css/layui.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/admin.css"/>
</head>
<body>
<div class="main-layout" id='main-layout'>
    <!--侧边栏-->
    <div class="main-layout-side">
        <a href="{% url 'home:index' %}"><div class="layui-logo">快递管理系统</div></a>
        <ul class="layui-nav layui-nav-tree" lay-filter="leftNav">
            {% if user.role == '3' %}
                <li class="layui-nav-item layui-nav-itemed user-order">
                    <a href="javascript:;"><i class="iconfont">&#xe607;</i>用户功能</a>
                    <dl class="layui-nav-child">
                        <dd><a class="l-line" data-id="userOrderCreate" data-url="{% url 'user:user_order_create' %}"
                               data-text="创建订单">创建订单</a>
                        </dd>
                        <dd><a class="l-line" data-id="userOrderSearch" data-url="{% url 'user:user_order_search' %}"
                               data-text="查询订单">查询订单</a>
                        </dd>
                        <dd><a class="l-line" data-id="userOrderHistory" data-url="{% url 'user:user_order_history' %}"
                               data-text="历史订单">历史订单</a>
                        </dd>
                    </dl>
                </li>
                <li class="layui-nav-item layui-nav-itemed user-order">
                    <a href="javascript:;"><i class="iconfont">&#xe608;</i>用户资料</a>
                    <dl class="layui-nav-child">
                        <dd><a class="l-line" data-id="userInfoRead" data-url="{% url 'user:user_info' %}"
                               data-text="个人资料">个人资料</a>
                        </dd>
                        <dd><a class="l-line" data-id="userPWChange" data-url="{% url 'user:user_pw_set' %}"
                               data-text="密码设置">密码设置</a>
                        </dd>
                    </dl>
                </li>
            {% elif user.role == '2' %}
                <li class="layui-nav-item layui-nav-itemed courier-order">
                    <a href="javascript:;"><i class="iconfont">&#xe608;</i>快递员功能</a>
                    <dl class="layui-nav-child">
                        <dd><a class="l-line" data-id="courierOrderCreate"
                               data-url="{% url 'courier:courier_order_create' %}" data-text="去接订单">去接订单</a></dd>
                        <dd><a class="l-line" data-id="courierOrderRead"
                               data-url="{% url 'courier:courier_order_read' %}" data-text="已接订单">已接订单</a></dd>
                        <dd><a class="l-line" data-id="courierOrderHistory"
                               data-url="{% url 'courier:courier_order_history' %}" data-text="历史订单">历史订单</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item layui-nav-itemed courier-order">
                    <a href="javascript:;"><i class="iconfont">&#xe608;</i>快递员信息</a>
                    <dl class="layui-nav-child">
                        <dd><a class="l-line" data-id="courierInfoRead" data-url="{% url 'courier:courier_info' %}"
                               data-text="快递员资料">快递员资料</a>
                        </dd>
                        <dd><a class="l-line" data-id="courierPWChange" data-url="{% url 'courier:courier_pw_set' %}"
                               data-text="密码设置">密码设置</a>
                        </dd>
                    </dl>
                </li>
            {% elif user.role == '1' %}
                <li class="layui-nav-item layui-nav-itemed ruler-order">
                    <a href="javascript:;"><i class="iconfont">&#xe608;</i>用户资料</a>
                    <dl class="layui-nav-child">
                        <dd><a class="l-line" data-id="allUserInfoRead" data-url="{% url 'ruler:ruler_user_read' %}"
                               data-text="用户资料">用户资料</a></dd>
                        <dd><a class="l-line" data-id="allUserOrderRead"
                               data-url="{% url 'ruler:ruler_user_order_read' %}" data-text="用户订单记录">用户订单记录</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item layui-nav-itemed ruler-order">
                    <a href="javascript:;"><i class="iconfont">&#xe608;</i>快递员资料</a>
                    <dl class="layui-nav-child">
                        <dd><a class="l-line" data-id="allCourierInfoRead"
                               data-url="{% url 'ruler:ruler_courier_read' %}" data-text="快递员资料">快递员资料</a></dd>
                        <dd><a class="l-line" data-id="allCourierOrderRead"
                               data-url="{% url 'ruler:ruler_courier_order_read' %}" data-text="快递员订单记录">快递员订单记录</a>
                        </dd>
                    </dl>
                </li>
            {% endif %}
        </ul>
    </div>
    <!--右侧内容-->
    <div class="main-layout-container">
        <!--头部-->
        <div class="main-layout-header">
            <div class="menu-btn" id="hideBtn">
                <a href="javascript:;">
                    <span class="iconfont">&#xe60e;</span>
                </a>
            </div>
            <ul class="layui-nav" lay-filter="rightNav">
                <li class="layui-nav-item">
                    <a href="javascript:;" data-url="admin-info.html" data-id='5'
                       data-text="个人信息">{{ user.username }}</a>
                </li>
                <li class="layui-nav-item"><a href="{% url 'home:logout' %}">退出</a></li>
            </ul>
        </div>
        <!--主体内容-->
        <div class="main-layout-body">
            <!--tab 切换-->
            <div class="layui-tab layui-tab-brief main-layout-tab" lay-filter="tab" lay-allowClose="true">
                <ul class="layui-tab-title">
                    <li class="layui-this welcome">后台主页</li>
                </ul>
                <div class="layui-tab-content">
                    <div class="layui-tab-item layui-show" style="background: #f5f5f5;">
                        <!--1-->
                        {% if user.role == '1' %}
                            <iframe src="/ruler/ruler_charts" width="100%" height="100%" name="iframe" scrolling="auto"
                                    class="iframe" framborder="0"></iframe>
                        {% endif %}
                        {% if user.role == '2' %}
                            <iframe src="/courier/courier_charts" width="100%" height="100%" name="iframe" scrolling="auto"
                                    class="iframe" framborder="0"></iframe>
                        {% endif %}
                        {% if user.role == '3' %}
                            <iframe src="/user/user_charts" width="100%" height="100%" name="iframe" scrolling="auto"
                                    class="iframe" framborder="0"></iframe>
                        {% endif %}
                        <!--1end-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--遮罩-->
    <div class="main-mask">

    </div>
</div>
<script type="text/javascript">
    var scope = {
        link: './welcome.html'
    }
</script>
<script src="/static/admin/layui/layui.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/admin/js/common.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/admin/js/main.js" type="text/javascript" charset="utf-8"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>登录</title>
    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/login/default.css" rel="stylesheet" type="text/css"/>
    <!--必要样式-->
    <link href="/static/css/login/styles.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/login/demo.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/login/loaders.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <link rel="stylesheet" href="/static/css/admin.css">

</head>
<body>
<div class='login'>
    {% if msg %}
        <script type="text/javascript">
            console.log('{{ msg }}');
            alert('{{ msg }}')
        </script>
    {% endif %}
    {% if form %}
        <script type="text/javascript">
            alert('未注册的用户名')
        </script>
    {% endif %}
    <div class="layui-form-item">
        <form class="layui-form" action="{% url 'home:login' %}" id="loginForm" method="post">
            {% csrf_token %}
            <div class='login_title'>
                <span>用户登录or</span><a href="{% url 'home:register' %}">去注册</a>
            </div>
            <div class='login_fields'>
                <div class="layui-form-item">
                    <div class='login_fields__user'>
                        <div class='icon'>
                            <img alt="" src=''>
                        </div>
                        <div class="layui-input-inline">
                            <input type="text" id="username" name="username" required
                                   lay-verify="required"
                                   placeholder="请填写用户名" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class='login_fields__password'>
                        <div class='icon'>
                            <img alt="" src=''>
                        </div>
                        <div class="layui-input-inline">
                            <input type="password" id="password" name="password" required
                                   lay-verify="required"
                                   placeholder="请填写密码" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class='login_fields__submit' align="center">
                        <div class="layui-input-block">
                            <!--<input type='button' value='登录'>-->
                            <button class="layui-btn" type="submit">登录</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class='disclaimer'>
                <div class="layui-form-item">
                    <a href="{% url 'courier:login' %}">快递员</a>
                    <span>&nbsp</span>
                    <a href="{% url 'ruler:login' %}">管理员</a>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript" src="/static/js/login/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/login/jquery-ui.min.js"></script>
<script type="text/javascript" src='/static/js/login/stopExecutionOnTimeout.js?t=1'></script>
<script type="text/javascript" src="/static/layui/layui.js"></script>
<script type="text/javascript" src="/static/js/login/Particleground.js"></script>
<script type="text/javascript" src="/static/js/login/Treatment.js"></script>
<script src="/static/js/jquery/jquery.cookie.js"></script>
<script src="/static/js/nginx.js"></script>
<script src="/static/js/login/login.js"></script>
<script type="text/javascript">

    // 粒子背景特效
    $('body').particleground({
        dotColor: '#E8DFE8',
        lineColor: '#133b88'
    });
</script>

</body>
</html>

templates/rulerCourierRead.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/layui/css/layui.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/admin.css"/>
</head>
<body>
<div style="margin-top: 40px">
    <span style="margin-left: 5%;">按收件人姓名查找</span>
</div>
<hr class="layui-bg-blue">
<div class="layui-form" id="table-list">
    <table class="layui-table" lay-even lay-skin="nob">
        <colgroup>
            <col width="50">
            <col class="hidden-xs" width="50">
            <col class="hidden-xs" width="100">
            <col width="100">
            <col class="hidden-xs" width="100">
            <col width="80">
            <col width="150">
        </colgroup>
        <thead>
        <tr>
            <th class="hidden-xs">ID</th>
            <th class="hidden-xs">快递员</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for courier in couriers %}
            <tr>
                <td class="hidden-xs">{{ courier.user_id }}</td>
                <td class="hidden-xs">{{ courier.username }}</td>
                <td>
                    <div class="layui-inline">
                        <a class="layui-btn layui-btn-mini layui-btn-normal" data-id="1"
                                href="{% url 'ruler:courier_detail' courier.id%}"><i class="layui-icon">&#xe642;</i></a>
                        <a class="layui-btn layui-btn-mini layui-btn-danger" onclick="courier_del({{ courier.id }})"><i class="layui-icon">&#xe640;</i></a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="page-wrap">
        <ul class="pagination">
            <li class="disabled"><span>«</span></li>
            <li class="active"><span>1</span></li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">»</a>
            </li>
        </ul>
    </div>
</div>
<script src="/static/js/jquery/jquery-3.3.1.js"></script>
<script src="/static/admin/layui/layui.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/admin/js/common.js" type="text/javascript" charset="utf-8"></script>
{% csrf_token %}
<script>
    function user_del(id) {
        var csrf = $('input[name = "csrfmiddlewaretoken"]').val()
        $.ajax({
            url: '/ruler/courier_del/' + id + '/',
            type: 'POST',
            dataType: 'json',
            headers: {'X-CSRFToken': csrf},
            success: function (data) {
                if (data.code == '200'){
                    window.location.reload()
                }
            },
            error: function (data) {
                alert('请求失败')
            }
        })
    }
</script>

</body>
</html>

templates/rulerLogin.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>登录</title>
    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/login/default.css" rel="stylesheet" type="text/css"/>
    <!--必要样式-->
    <link href="/static/css/login/styles.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/login/demo.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/login/loaders.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <link rel="stylesheet" href="/static/css/admin.css">

</head>
<body>
<div class='login'>
    <div class="layui-form-item">
        <form class="layui-form" action="" id="loginForm" method="post">
            {% csrf_token %}
            <div class='login_title'>
                <span>管理员登录</span>
            </div>
            <div class='login_fields'>
                <div class="layui-form-item">
                    <div class='login_fields__user'>
                        <div class='icon'>
                            <img alt="" src=''>
                        </div>
                        <div class="layui-input-inline">
                            <input type="text" id="username" name="username" required
                                   lay-verify="required"
                                   placeholder="请填写用户名" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class='login_fields__password'>
                        <div class='icon'>
                            <img alt="" src=''>
                        </div>
                        <div class="layui-input-inline">
                            <input type="password" id="password" name="password" required
                                   lay-verify="required"
                                   placeholder="请填写密码" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class='login_fields__submit' align="center">
                        <div class="layui-input-block">
                            <!--<input type='button' value='登录'>-->
                            <button class="layui-btn" type="submit">登录</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class='disclaimer'>
                <div class="layui-form-item">
                    <a href="{% url 'home:login' %}">普通用户</a>
                    <span>&nbsp</span>
                    <a href="{% url 'courier:login' %}">快递员</a>
                </div>
            </div>
        </form>
    </div>
</div>


<script type="text/javascript" src="/static/js/login/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/login/jquery-ui.min.js"></script>
<script type="text/javascript" src='/static/js/login/stopExecutionOnTimeout.js?t=1'></script>
<script type="text/javascript" src="/static/layui/layui.js"></script>
<script type="text/javascript" src="/static/js/login/Particleground.js"></script>
<script type="text/javascript" src="/static/js/login/Treatment.js"></script>
<script src="/static/js/jquery/jquery.cookie.js"></script>
<script src="/static/js/nginx.js"></script>
<script src="/static/js/login/login.js"></script>
<script type="text/javascript">

    // 粒子背景特效
    $('body').particleground({
        dotColor: '#E8DFE8',
        lineColor: '#133b88'
    });

</script>

</body>
</html>

templates/userOrderSearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>司机信息详情页</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/layui/css/layui.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/admin.css"/>
</head>
<body>
<div>
    <div style="margin-top: 40px">
        <span style="margin-left: 5%;">按收件人姓名查找</span>
    </div>
    <hr class="layui-bg-blue">
    <form method="get" action="{% url 'user:user_order_search' %}">

        <div class="layui-form-item">
            <label class="layui-form-label">姓名</label>
            <div class="layui-input-inline">
                <input type="text" name="signerName" autocomplete="off" class="layui-input"
                       placeholder="{{ signer_name }}">
            </div>
            <div style="float: left;">
                <button type="submit" class="layui-btn layui-btn-radius layui-btn-normal">查询</button>
            </div>
        </div>
    </form>
    <hr class="layui-bg-blue">
    <div class="layui-form" id="table-list">
        <table class="layui-table" lay-even lay-skin="nob">
            <colgroup>
                <col width="50">
                <col class="hidden-xs" width="50">
                <col class="hidden-xs" width="100">
                <col width="100">
                <col class="hidden-xs" width="100">
                <col width="80">
                <col width="150">
            </colgroup>
            <thead>
            <tr>
                <th class="hidden-xs">ID</th>
                <th class="hidden-xs">寄件人</th>
                <th>收件人</th>
                <th>发布时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td class="hidden-xs">{{ order.id }}</td>
                    <td class="hidden-xs">{{ order.user.username }}</td>
                    <td>{{ order.signer.signer_name }}</td>
                    <td>{{ order.add_time }}</td>
                    <td>
                        {% if order.courier_id %}
                            已接/{{ order.courier.username }}
                        {% else %}
                            未接
                        {% endif %}
                    </td>
                    <td>
                        <div class="layui-inline">
                            {% if not order.courier.username %}
                            <a class="layui-btn layui-btn-mini layui-btn-danger" onclick="order_delete({{ order.id }})"><i class="layui-icon">&#xe640;</i></a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="page-wrap">
            <ul class="pagination">
                <li class="disabled"><span>«</span></li>
                <li class="active"><span>1</span></li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>

</div>
<script src="/static/js/jquery/jquery-3.3.1.js"></script>
<script src="/static/admin/layui/layui.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/admin/js/common.js" type="text/javascript" charset="utf-8"></script>
{% csrf_token %}
<script>
    function order_delete(id) {
        var csrf = $('input[name = "csrfmiddlewaretoken"]').val()
        $.ajax({
            url: '/user/order_del/' + id + '/',
            type: 'POST',
            dataType: 'json',
            headers: {'X-CSRFToken': csrf},
            success: function (data) {
                if (data.code == '200') {
                    alert('删除成功')
                    window.location.reload()
                }

            },
            error: function (data) {
                alert('请求失败')
            }
        })
    }

    layui.use(['form', 'jquery', 'layer', 'dialog'], function () {
        var $ = layui.jquery;

        //修改状态
        $('#table-list').on('click', '.table-list-status', function () {
            var That = $(this);
            var status = That.attr('data-status');
            var id = That.parent().attr('data-id');
            if (status == 1) {
                That.removeClass('layui-btn-normal').addClass('layui-btn-warm').html('隐藏').attr('data-status', 2);
            } else if (status == 2) {
                That.removeClass('layui-btn-warm').addClass('layui-btn-normal').html('显示').attr('data-status', 1);

            }
        })
        //列表删除
    });
</script>
{#{% csrf_token %}#}
{#<script type="text/javascript">#}
{#    function search_by_signerName() {#}
{#        alert('请求')#}
{#        var signername = $('#signerName').val()#}
{#        var csrf = $('input[name="csrfmiddlewaretoken"]').val()#}
{#        $.ajax({#}
{#            url: '/user/user_order_search',#}
{#            type: 'POST',#}
{#            dataType: 'json',#}
{#            headers: {'X-CSRFToken': csrf},#}
{#            data: {'signerName': signername},#}
{#            success: function (data) {#}
{#location.href = '{% url 'user:user_order_search' %}'#}
{#            },#}
{#            error: function () {#}
{#                alert('失败')#}
{#            }#}
{#        });#}
{#    }#}
{#</script>#}

</body>
</html>